apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::882040517196:role/JenkinsServerRole
      username: jenkins
      groups:
        - system:masters
