apiVersion: v1
kind: ServiceAccount
metadata:
  name: springboot-app-sa
  namespace: production
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::882040517196:role/eksctl-my-eks-cluster-addon-iamserviceaccount-Role1-kqQaSyiVZnIu